export const BASE_URL = "https://api.themoviedb.org/3/movie"
export const UPCOMING_URL = "/upcoming"
export const IMAGE_BASE_URL= "https://image.tmdb.org/t/p/w500"
export const TOP_RATED_URL = "/top_rated"
export const NOW_PLAYING_URL = "/now_playing"
export const POPULAR_URL = "/popular"